<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\DataAppWinform\dm1\DBMS\DBMS\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\DataAppWinform\dm1\DBMS\DBMS\.editorconfig" />
  </ItemGroup>

</Project>